AppSettings:
  SiteTitle: This is the development application file - LAB Module
  TemplateID: csi-template-new
  CacheDbResults: true
Logging: 
  IncludeScopes: false
  LogLevel: 
    Default: Debug
    System: Information
    Microsoft: Information
eureka:
  client:
    serviceUrl: https://csi-eurekaserver.run.aws-usw02-pr.ice.predix.io/eureka/
mysql:
  client:
    server: localhost
redis:
  client:
    host: localhost
