server:
  port: 8888
  
management:
  context-path: /admin
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
    preferIpAddress: true

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/devlkcsi/Config-Repo

---
#spring:
#  profiles: csi
eureka:
  password: password
  instance:
#    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: ${url.service-registry}/eureka/
      preferIpAddress: false
      
