AppSettings:
  SiteTitle: CSI-NET-PATIENTS-01-OracleDev
  CacheDbResults: true
Logging: 
  IncludeScopes: false
  LogLevel: 
    Default: Debug
    System: Information
    Microsoft: Information
eureka:
  client:
    serviceUrl: http://129.213.29.71:31647/eureka/
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: false
    securePortEnabled: true
  server:
    enableSelfPreservation: false
mysql:
  client:
    server: localhost
redis:
  client:
    host: localhost
