AppSettings:
  SiteTitle: CSI-SVR-CONFIGSVR-01-OracleDev
  TemplateID: csi-template-new
  CacheDbResults: true
Logging: 
  IncludeScopes: false
  LogLevel: 
    Default: Debug
    System: Information
    Microsoft: Information
eureka:
  client:
    serviceUrl:
      defaultZone: http://129.213.29.71:31647//eureka
    registerWithEureka: true
    fetchRegistry: true
mysql:
  client:
    server: localhost
redis:
  client:
    host: localhost
